name: generate-sdks

on:
  push:
    tags:
      - "*"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Fern
        run: npm install -g fern-api

      - name: Generate SDKs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --group publish --log-level debug --version ${{ github.ref_name }}
